export const descriptions = {
  Medicare:
    "Medicare is a federal health insurance program for people aged 65 and older or younger people with certain conditions.  Introduced by Medicare Modernization Act of 2003,types of coverage include Medicare Part A - hospital insurance for inpatient hospital care, skilled nursing facilities, hospice, and some home healthcare. Medicare Part B - medical Insurance for outpatient care, physician services, and preventive services. Medicare Part C - allowing beneficiaries to receive their Medicare benefits through private insurance companies instead of traditional Medicare. Medicare Part D - the prescription drug benefit, which provides coverage for prescription medications through private insurance plans. Medicaid Services - a health insurance program that provides coverage for low-income individuals and families, including children, pregnant women, elderly adults, and people with disabilities. Medicaid covers healthcare services like doctor visits, hospital stays, long-term care, and other medical expenses. It is primarily for people who meet specific income and eligibility criteria. The Affordable Care Act of 2010 significantly expands healthcare coverage through Medicaid eligibility to more low-income individuals and families. The Inflation Reduction Act of 2022 allows Medicare to negotiate drug prices with pharmaceutical companies for certain high-cost drugs. This reform penalizes drug manufacturers for excessive price increases that exceed inflation, thus lowering prices for Medicare beneficiaries. The act generates revenue for the U.S. government and reduces deficits, as well as funds climate initiatives investing in renewable energy projects and incentives for green technology.",

  "National Defense":
    "The National Defense Authorization Act (NDAA) specifies the national budget of the U.S. Department of Defense for every fiscal year. Key features include military pay raises, healthcare and support for military families, atomic energy defense, security of the U.S. nuclear arsenal, and support for allies. For instance, The Consolidated Appropriations Act of 2023, for instance, determines the amount of funding for emergency assistance in foreign nations, such as Ukraine, Israel, and defense partnerships in the Indo-Pacific region. Specifically, the act  guarantees $80,000,000 to provide to the Government of Israel for the procurement of the Iron Dome, a defense system countersing short-range rocket threats and $127,000,000 to the Short Range Ballistic Missile Defense program. ",

  "Education, Training, Employment, and Social Services":
    " Federal funding for K-12 education is upheld by the Elementary and Secondary Education Act (ESEA). Legislation was originally signed in 1965 by President Lyndon B. Johnson and is still in effect today via several reauthorizing bills, most prominently the No Child Left Behind Act in 2001. The Higher Education Act (HEA) of 1965 establishes a federal student loan program, including Direct Loans, to provide students with financial assistance and access to higher education. The Individuals with Disabilities Education Act (IDEA) ensures federal funding for students with disabilities to receive proper education and social services.",

  "Social Security":
    "In 1965, Lyndon B. Johnson signed The Social Security Act into law that laid the foundation for the U.S. social insurance system. Retirees, disabled individuals, and survivors of deceased workers are provided with cash benefits in order to replace a portion of their income. Compensation comes in the form of retirement benefits, disability insurance, and survivor benefits.",

  Transportation:
    "The Infrastructure Investment and Jobs Act, IIJA, also known as the Bipartisan Infrastructure Law, significantly increased funding for transportation infrastructure, including roads, bridges, public transit, rail, and broadband. The IIJA provides an infusion of federal funding and establishes multi-year funding levels for various transportation programs, directly affecting how federal income tax revenues are used for transportation projects. The Transportation Equity Act - The Transportation Equity Act for the 21st Century (TEA-21) and subsequent reauthorizations have established funding formulas for various transportation projects, ensuring that federal funds are allocated to different types of transportation infrastructure, including highways, transit, and safety programs.Airport and Airway Improvement Act established the Airport Improvement Program which outlines how federal funds are allocated to enhance the safety, capacity, and efficiency of the national air transportation system. The Water Resources Development Act authorizes projects to maintain and improve the nation’s water resources infrastructure, including navigation, flood control, and ecosystem restoration.",

  "Veterans Benefits and Services":
    "The G.I. Bill provides educational benefits, housing assistance, and other resources for veterans. The PACT Act of 2022 increases eligibility for veterans exposed to toxic substances through additional funding for treatment related to toxic exposure.",

  "National Resources and Environment":
    "The National Environmental Policy Act (NEPA) establishes a framework for environmental protection in the U.S. It requires federal agencies to assess the environmental impacts of proposed projects, including those funded by federal income taxes, before making decisions. NEPA impacts federal funding allocation by requiring environmental assessments and impact statements for projects related to infrastructure, natural resources, and other federally funded activities.",

  "Administration Of Justice":
    "Omnibus Crime Control and Safe Streets Act establishes the foundation for federal funding to state and local law enforcement agencies, creating the Law Enforcement Assistance Administration (LEAA) to support programs that combat crime, improve public safety, and modernize policing. The act introduced grants that continue today under various programs, administered by the Department of Justice (DOJ), which are funded by federal income tax revenues. The USA PATRIOT Act (2001) was enacted following the September 11 attacks and expands federal law enforcement’s authority to combat terrorism, surveillance, and financial crimes. It established funding for anti-terrorism efforts and increased DOJ and Department of Homeland Security (DHS) resources, including grants to state and local law enforcement for counter-terrorism initiatives, funded by federal tax revenues.",

  "Community and Regional Development":
    "The Disaster Relief and Emergency Assistance Act of 1988 provides the legal framework for federal disaster relief funding through the Federal Emergency Management Agency (FEMA). It allocates funds for disaster response, recovery, and rebuilding in areas affected by natural disasters. Federal income taxes contribute to the Disaster Relief Fund (DRF), which provides critical assistance to communities and regional governments affected by disasters.",

  "International Affairs":
    "The International Disaster Assistance (IDA) Program provides funding from federal income tax revenues allocated by Congress for humanitarian assistance during international crises, including natural disasters and health emergencies. The funds are managed by USAID’s Bureau for Humanitarian Assistance (BHA) and are allocated to provide emergency food aid, shelter, water, sanitation, and health services.",

  Agriculture:
    "The primary legislation for U.S. agricultural policy is the Agriculture Improvement Act which occurs every 5 years. The most recent version, the Agriculture Improvement Act of 2018, includes programs for crop insurance, commodity price supports, agricultural research, rural development, and conservation.",

  "General Government":
    "The Antideficiency Act prohibits federal agencies from spending more than the amount appropriated by Congress and from incurring obligations in advance of appropriations. This act is critical for maintaining fiscal discipline, ensuring that federal income tax revenues are used according to the budgetary constraints set by Congress and that the government operates within its financial means.",

  "Commerce and Housing Credit":
    "The National Housing Act established the Federal Housing Administration (FHA) and aims to improve housing standards and conditions. It provides mortgage insurance for lenders, encouraging them to make loans for home purchases and multifamily housing development, thereby influencing how federal income taxes can support housing finance.",

  "Net Interest":
    "Net interest refers to the amount of interest expense incurred by the government on its outstanding debt, minus any interest income earned from its investments or other sources. This concept is particularly relevant in the context of federal budgeting and fiscal policy.",

  Energy:
    "The American Recovery and Reinvestment Act (ARRA) provides funding for clean energy programs, energy efficiency improvements, and renewable energy projects. It included funding for weatherization assistance, grid modernization, and loan guarantees for renewable energy projects, directly impacting how federal income taxes were used to support energy initiatives.",
};
