name: Deploy to S3

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.1.0' # specify your node version
          

      - name: Install dependencies
        run: npm install
        working-directory: ./frontend # change to your actual directory where package.json is located

      - name: Build the project
        run: npm run build
        working-directory: ./frontend # change to your actual directory

      - name: ls
        run: ls ./frontend && ls

      - name: Sync build to S3
        run: aws s3 sync build s3://fiscalfootprint-fe1 --delete
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
